version: '3.8'

services:
  # Servicio de Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: msms_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msms_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Servicio Backend NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msms_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Conecta a la base de datos de arriba. 
      # Usamos el nombre del servicio (db) como host.
      - DATABASE_URL=postgresql://user:password@db:5432/msms_db?schema=public
      - NODE_ENV=production
    depends_on:
      - db

  # Servicio Frontend Next.js
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: msms_frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=preproduction
    depends_on:
      - api

  # Caché: Redis (Pre-producción / Producción)
  redis:
    image: redis:7-alpine
    container_name: msms_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Almacenamiento de objetos: MinIO (Pre-producción)
  minio:
    image: minio/minio
    container_name: msms_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  redis_data:
  minio_data:
