// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI debe usar la conexión directa de Neon para migraciones.
    // El backend conserva DATABASE_URL (agrupada) en tiempo de ejecución.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
